-- Add/update regions (run after supabase-setup.sql)

INSERT INTO "Region" ("id","name","slug","state","lat","lng","radiusKm") VALUES ('reg_san_francisco','San Francisco','san-francisco','CA',37.7749,-122.4194,20) ON CONFLICT ("slug") DO UPDATE SET "name"=EXCLUDED."name","state"=EXCLUDED."state","lat"=EXCLUDED."lat","lng"=EXCLUDED."lng","radiusKm"=EXCLUDED."radiusKm";
INSERT INTO "Region" ("id","name","slug","state","lat","lng","radiusKm") VALUES ('reg_new_york_city','New York City','new-york-city','NY',40.7128,-74.006,25) ON CONFLICT ("slug") DO UPDATE SET "name"=EXCLUDED."name","state"=EXCLUDED."state","lat"=EXCLUDED."lat","lng"=EXCLUDED."lng","radiusKm"=EXCLUDED."radiusKm";
INSERT INTO "Region" ("id","name","slug","state","lat","lng","radiusKm") VALUES ('reg_los_angeles','Los Angeles','los-angeles','CA',34.0522,-118.2437,30) ON CONFLICT ("slug") DO UPDATE SET "name"=EXCLUDED."name","state"=EXCLUDED."state","lat"=EXCLUDED."lat","lng"=EXCLUDED."lng","radiusKm"=EXCLUDED."radiusKm";
INSERT INTO "Region" ("id","name","slug","state","lat","lng","radiusKm") VALUES ('reg_chicago','Chicago','chicago','IL',41.8781,-87.6298,30) ON CONFLICT ("slug") DO UPDATE SET "name"=EXCLUDED."name","state"=EXCLUDED."state","lat"=EXCLUDED."lat","lng"=EXCLUDED."lng","radiusKm"=EXCLUDED."radiusKm";
INSERT INTO "Region" ("id","name","slug","state","lat","lng","radiusKm") VALUES ('reg_houston','Houston','houston','TX',29.7604,-95.3698,35) ON CONFLICT ("slug") DO UPDATE SET "name"=EXCLUDED."name","state"=EXCLUDED."state","lat"=EXCLUDED."lat","lng"=EXCLUDED."lng","radiusKm"=EXCLUDED."radiusKm";
INSERT INTO "Region" ("id","name","slug","state","lat","lng","radiusKm") VALUES ('reg_phoenix','Phoenix','phoenix','AZ',33.4484,-112.074,35) ON CONFLICT ("slug") DO UPDATE SET "name"=EXCLUDED."name","state"=EXCLUDED."state","lat"=EXCLUDED."lat","lng"=EXCLUDED."lng","radiusKm"=EXCLUDED."radiusKm";
INSERT INTO "Region" ("id","name","slug","state","lat","lng","radiusKm") VALUES ('reg_philadelphia','Philadelphia','philadelphia','PA',39.9526,-75.1652,25) ON CONFLICT ("slug") DO UPDATE SET "name"=EXCLUDED."name","state"=EXCLUDED."state","lat"=EXCLUDED."lat","lng"=EXCLUDED."lng","radiusKm"=EXCLUDED."radiusKm";
INSERT INTO "Region" ("id","name","slug","state","lat","lng","radiusKm") VALUES ('reg_san_antonio','San Antonio','san-antonio','TX',29.4241,-98.4936,30) ON CONFLICT ("slug") DO UPDATE SET "name"=EXCLUDED."name","state"=EXCLUDED."state","lat"=EXCLUDED."lat","lng"=EXCLUDED."lng","radiusKm"=EXCLUDED."radiusKm";
INSERT INTO "Region" ("id","name","slug","state","lat","lng","radiusKm") VALUES ('reg_san_diego','San Diego','san-diego','CA',32.7157,-117.1611,30) ON CONFLICT ("slug") DO UPDATE SET "name"=EXCLUDED."name","state"=EXCLUDED."state","lat"=EXCLUDED."lat","lng"=EXCLUDED."lng","radiusKm"=EXCLUDED."radiusKm";
INSERT INTO "Region" ("id","name","slug","state","lat","lng","radiusKm") VALUES ('reg_dallas','Dallas','dallas','TX',32.7767,-96.797,35) ON CONFLICT ("slug") DO UPDATE SET "name"=EXCLUDED."name","state"=EXCLUDED."state","lat"=EXCLUDED."lat","lng"=EXCLUDED."lng","radiusKm"=EXCLUDED."radiusKm";
INSERT INTO "Region" ("id","name","slug","state","lat","lng","radiusKm") VALUES ('reg_austin','Austin','austin','TX',30.2672,-97.7431,30) ON CONFLICT ("slug") DO UPDATE SET "name"=EXCLUDED."name","state"=EXCLUDED."state","lat"=EXCLUDED."lat","lng"=EXCLUDED."lng","radiusKm"=EXCLUDED."radiusKm";
INSERT INTO "Region" ("id","name","slug","state","lat","lng","radiusKm") VALUES ('reg_jacksonville','Jacksonville','jacksonville','FL',30.3322,-81.6557,35) ON CONFLICT ("slug") DO UPDATE SET "name"=EXCLUDED."name","state"=EXCLUDED."state","lat"=EXCLUDED."lat","lng"=EXCLUDED."lng","radiusKm"=EXCLUDED."radiusKm";
INSERT INTO "Region" ("id","name","slug","state","lat","lng","radiusKm") VALUES ('reg_fort_worth','Fort Worth','fort-worth','TX',32.7555,-97.3308,30) ON CONFLICT ("slug") DO UPDATE SET "name"=EXCLUDED."name","state"=EXCLUDED."state","lat"=EXCLUDED."lat","lng"=EXCLUDED."lng","radiusKm"=EXCLUDED."radiusKm";
INSERT INTO "Region" ("id","name","slug","state","lat","lng","radiusKm") VALUES ('reg_columbus','Columbus','columbus','OH',39.9612,-82.9988,30) ON CONFLICT ("slug") DO UPDATE SET "name"=EXCLUDED."name","state"=EXCLUDED."state","lat"=EXCLUDED."lat","lng"=EXCLUDED."lng","radiusKm"=EXCLUDED."radiusKm";
INSERT INTO "Region" ("id","name","slug","state","lat","lng","radiusKm") VALUES ('reg_charlotte','Charlotte','charlotte','NC',35.2271,-80.8431,30) ON CONFLICT ("slug") DO UPDATE SET "name"=EXCLUDED."name","state"=EXCLUDED."state","lat"=EXCLUDED."lat","lng"=EXCLUDED."lng","radiusKm"=EXCLUDED."radiusKm";
INSERT INTO "Region" ("id","name","slug","state","lat","lng","radiusKm") VALUES ('reg_indianapolis','Indianapolis','indianapolis','IN',39.7684,-86.1581,30) ON CONFLICT ("slug") DO UPDATE SET "name"=EXCLUDED."name","state"=EXCLUDED."state","lat"=EXCLUDED."lat","lng"=EXCLUDED."lng","radiusKm"=EXCLUDED."radiusKm";
INSERT INTO "Region" ("id","name","slug","state","lat","lng","radiusKm") VALUES ('reg_san_jose','San Jose','san-jose','CA',37.3382,-121.8863,20) ON CONFLICT ("slug") DO UPDATE SET "name"=EXCLUDED."name","state"=EXCLUDED."state","lat"=EXCLUDED."lat","lng"=EXCLUDED."lng","radiusKm"=EXCLUDED."radiusKm";
INSERT INTO "Region" ("id","name","slug","state","lat","lng","radiusKm") VALUES ('reg_denver','Denver','denver','CO',39.7392,-104.9903,30) ON CONFLICT ("slug") DO UPDATE SET "name"=EXCLUDED."name","state"=EXCLUDED."state","lat"=EXCLUDED."lat","lng"=EXCLUDED."lng","radiusKm"=EXCLUDED."radiusKm";
INSERT INTO "Region" ("id","name","slug","state","lat","lng","radiusKm") VALUES ('reg_seattle','Seattle','seattle','WA',47.6062,-122.3321,25) ON CONFLICT ("slug") DO UPDATE SET "name"=EXCLUDED."name","state"=EXCLUDED."state","lat"=EXCLUDED."lat","lng"=EXCLUDED."lng","radiusKm"=EXCLUDED."radiusKm";
INSERT INTO "Region" ("id","name","slug","state","lat","lng","radiusKm") VALUES ('reg_boston','Boston','boston','MA',42.3601,-71.0589,25) ON CONFLICT ("slug") DO UPDATE SET "name"=EXCLUDED."name","state"=EXCLUDED."state","lat"=EXCLUDED."lat","lng"=EXCLUDED."lng","radiusKm"=EXCLUDED."radiusKm";
INSERT INTO "Region" ("id","name","slug","state","lat","lng","radiusKm") VALUES ('reg_portland','Portland','portland','OR',45.5152,-122.6784,25) ON CONFLICT ("slug") DO UPDATE SET "name"=EXCLUDED."name","state"=EXCLUDED."state","lat"=EXCLUDED."lat","lng"=EXCLUDED."lng","radiusKm"=EXCLUDED."radiusKm";
INSERT INTO "Region" ("id","name","slug","state","lat","lng","radiusKm") VALUES ('reg_nashville','Nashville','nashville','TN',36.1627,-86.7816,30) ON CONFLICT ("slug") DO UPDATE SET "name"=EXCLUDED."name","state"=EXCLUDED."state","lat"=EXCLUDED."lat","lng"=EXCLUDED."lng","radiusKm"=EXCLUDED."radiusKm";
INSERT INTO "Region" ("id","name","slug","state","lat","lng","radiusKm") VALUES ('reg_las_vegas','Las Vegas','las-vegas','NV',36.1699,-115.1398,30) ON CONFLICT ("slug") DO UPDATE SET "name"=EXCLUDED."name","state"=EXCLUDED."state","lat"=EXCLUDED."lat","lng"=EXCLUDED."lng","radiusKm"=EXCLUDED."radiusKm";
INSERT INTO "Region" ("id","name","slug","state","lat","lng","radiusKm") VALUES ('reg_atlanta','Atlanta','atlanta','GA',33.749,-84.388,30) ON CONFLICT ("slug") DO UPDATE SET "name"=EXCLUDED."name","state"=EXCLUDED."state","lat"=EXCLUDED."lat","lng"=EXCLUDED."lng","radiusKm"=EXCLUDED."radiusKm";
INSERT INTO "Region" ("id","name","slug","state","lat","lng","radiusKm") VALUES ('reg_miami','Miami','miami','FL',25.7617,-80.1918,25) ON CONFLICT ("slug") DO UPDATE SET "name"=EXCLUDED."name","state"=EXCLUDED."state","lat"=EXCLUDED."lat","lng"=EXCLUDED."lng","radiusKm"=EXCLUDED."radiusKm";
INSERT INTO "Region" ("id","name","slug","state","lat","lng","radiusKm") VALUES ('reg_minneapolis','Minneapolis','minneapolis','MN',44.9778,-93.265,30) ON CONFLICT ("slug") DO UPDATE SET "name"=EXCLUDED."name","state"=EXCLUDED."state","lat"=EXCLUDED."lat","lng"=EXCLUDED."lng","radiusKm"=EXCLUDED."radiusKm";
INSERT INTO "Region" ("id","name","slug","state","lat","lng","radiusKm") VALUES ('reg_tampa','Tampa','tampa','FL',27.9506,-82.4572,30) ON CONFLICT ("slug") DO UPDATE SET "name"=EXCLUDED."name","state"=EXCLUDED."state","lat"=EXCLUDED."lat","lng"=EXCLUDED."lng","radiusKm"=EXCLUDED."radiusKm";
INSERT INTO "Region" ("id","name","slug","state","lat","lng","radiusKm") VALUES ('reg_new_orleans','New Orleans','new-orleans','LA',29.9511,-90.0715,25) ON CONFLICT ("slug") DO UPDATE SET "name"=EXCLUDED."name","state"=EXCLUDED."state","lat"=EXCLUDED."lat","lng"=EXCLUDED."lng","radiusKm"=EXCLUDED."radiusKm";
INSERT INTO "Region" ("id","name","slug","state","lat","lng","radiusKm") VALUES ('reg_pittsburgh','Pittsburgh','pittsburgh','PA',40.4406,-79.9959,25) ON CONFLICT ("slug") DO UPDATE SET "name"=EXCLUDED."name","state"=EXCLUDED."state","lat"=EXCLUDED."lat","lng"=EXCLUDED."lng","radiusKm"=EXCLUDED."radiusKm";
INSERT INTO "Region" ("id","name","slug","state","lat","lng","radiusKm") VALUES ('reg_sacramento','Sacramento','sacramento','CA',38.5816,-121.4944,25) ON CONFLICT ("slug") DO UPDATE SET "name"=EXCLUDED."name","state"=EXCLUDED."state","lat"=EXCLUDED."lat","lng"=EXCLUDED."lng","radiusKm"=EXCLUDED."radiusKm";

-- Done. 30 regions total.
